# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: F:/OLEDrgb/pins.xdc

# Block Designs: bd/OLEDrgb_Block/OLEDrgb_Block.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OLEDrgb_Block || ORIG_REF_NAME==OLEDrgb_Block} -quiet] -quiet

# IP: bd/OLEDrgb_Block/ip/OLEDrgb_Block_microblaze_0_0/OLEDrgb_Block_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OLEDrgb_Block_microblaze_0_0 || ORIG_REF_NAME==OLEDrgb_Block_microblaze_0_0} -quiet] -quiet

# IP: bd/OLEDrgb_Block/ip/OLEDrgb_Block_dlmb_v10_0/OLEDrgb_Block_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OLEDrgb_Block_dlmb_v10_0 || ORIG_REF_NAME==OLEDrgb_Block_dlmb_v10_0} -quiet] -quiet

# IP: bd/OLEDrgb_Block/ip/OLEDrgb_Block_ilmb_v10_0/OLEDrgb_Block_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OLEDrgb_Block_ilmb_v10_0 || ORIG_REF_NAME==OLEDrgb_Block_ilmb_v10_0} -quiet] -quiet

# IP: bd/OLEDrgb_Block/ip/OLEDrgb_Block_dlmb_bram_if_cntlr_0/OLEDrgb_Block_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OLEDrgb_Block_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==OLEDrgb_Block_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/OLEDrgb_Block/ip/OLEDrgb_Block_ilmb_bram_if_cntlr_0/OLEDrgb_Block_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OLEDrgb_Block_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==OLEDrgb_Block_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/OLEDrgb_Block/ip/OLEDrgb_Block_lmb_bram_0/OLEDrgb_Block_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OLEDrgb_Block_lmb_bram_0 || ORIG_REF_NAME==OLEDrgb_Block_lmb_bram_0} -quiet] -quiet

# IP: bd/OLEDrgb_Block/ip/OLEDrgb_Block_mdm_1_0/OLEDrgb_Block_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OLEDrgb_Block_mdm_1_0 || ORIG_REF_NAME==OLEDrgb_Block_mdm_1_0} -quiet] -quiet

# IP: bd/OLEDrgb_Block/ip/OLEDrgb_Block_clk_wiz_1_0/OLEDrgb_Block_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OLEDrgb_Block_clk_wiz_1_0 || ORIG_REF_NAME==OLEDrgb_Block_clk_wiz_1_0} -quiet] -quiet

# IP: bd/OLEDrgb_Block/ip/OLEDrgb_Block_rst_clk_wiz_1_100M_0/OLEDrgb_Block_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OLEDrgb_Block_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==OLEDrgb_Block_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/OLEDrgb_Block/ip/OLEDrgb_Block_PmodOLEDrgb_0_0/OLEDrgb_Block_PmodOLEDrgb_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OLEDrgb_Block_PmodOLEDrgb_0_0 || ORIG_REF_NAME==OLEDrgb_Block_PmodOLEDrgb_0_0} -quiet] -quiet

# IP: bd/OLEDrgb_Block/ip/OLEDrgb_Block_reset_inv_0_0/OLEDrgb_Block_reset_inv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OLEDrgb_Block_reset_inv_0_0 || ORIG_REF_NAME==OLEDrgb_Block_reset_inv_0_0} -quiet] -quiet

# IP: bd/OLEDrgb_Block/ip/OLEDrgb_Block_axi_smc_0/OLEDrgb_Block_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OLEDrgb_Block_axi_smc_0 || ORIG_REF_NAME==OLEDrgb_Block_axi_smc_0} -quiet] -quiet

# IP: bd/OLEDrgb_Block/ip/OLEDrgb_Block_axi_uartlite_0_0/OLEDrgb_Block_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OLEDrgb_Block_axi_uartlite_0_0 || ORIG_REF_NAME==OLEDrgb_Block_axi_uartlite_0_0} -quiet] -quiet

# XDC: f:/OLEDrgb/OLEDrgb.gen/sources_1/bd/OLEDrgb_Block/OLEDrgb_Block_ooc.xdc
