# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: F:/esp32/pins.xdc

# Block Designs: F:/Project AHE/esp32_system/esp32_system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==esp32_system || ORIG_REF_NAME==esp32_system} -quiet] -quiet

# IP: F:/Project AHE/esp32_system/ip/esp32_system_microblaze_0_0/esp32_system_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==esp32_system_microblaze_0_0 || ORIG_REF_NAME==esp32_system_microblaze_0_0} -quiet] -quiet

# IP: F:/Project AHE/esp32_system/ip/esp32_system_dlmb_v10_0/esp32_system_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==esp32_system_dlmb_v10_0 || ORIG_REF_NAME==esp32_system_dlmb_v10_0} -quiet] -quiet

# IP: F:/Project AHE/esp32_system/ip/esp32_system_ilmb_v10_0/esp32_system_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==esp32_system_ilmb_v10_0 || ORIG_REF_NAME==esp32_system_ilmb_v10_0} -quiet] -quiet

# IP: F:/Project AHE/esp32_system/ip/esp32_system_dlmb_bram_if_cntlr_0/esp32_system_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==esp32_system_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==esp32_system_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: F:/Project AHE/esp32_system/ip/esp32_system_ilmb_bram_if_cntlr_0/esp32_system_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==esp32_system_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==esp32_system_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: F:/Project AHE/esp32_system/ip/esp32_system_lmb_bram_0/esp32_system_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==esp32_system_lmb_bram_0 || ORIG_REF_NAME==esp32_system_lmb_bram_0} -quiet] -quiet

# IP: F:/Project AHE/esp32_system/ip/esp32_system_mdm_1_0/esp32_system_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==esp32_system_mdm_1_0 || ORIG_REF_NAME==esp32_system_mdm_1_0} -quiet] -quiet

# IP: F:/Project AHE/esp32_system/ip/esp32_system_clk_wiz_1_0/esp32_system_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==esp32_system_clk_wiz_1_0 || ORIG_REF_NAME==esp32_system_clk_wiz_1_0} -quiet] -quiet

# IP: F:/Project AHE/esp32_system/ip/esp32_system_rst_clk_wiz_1_100M_0/esp32_system_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==esp32_system_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==esp32_system_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: F:/Project AHE/esp32_system/ip/esp32_system_axi_uartlite_1_0/esp32_system_axi_uartlite_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==esp32_system_axi_uartlite_1_0 || ORIG_REF_NAME==esp32_system_axi_uartlite_1_0} -quiet] -quiet

# IP: F:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/esp32_system_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==esp32_system_axi_smc_0 || ORIG_REF_NAME==esp32_system_axi_smc_0} -quiet] -quiet

# IP: F:/Project AHE/esp32_system/ip/esp32_system_reset_inv_0_0/esp32_system_reset_inv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==esp32_system_reset_inv_0_0 || ORIG_REF_NAME==esp32_system_reset_inv_0_0} -quiet] -quiet

# IP: F:/Project AHE/esp32_system/ip/esp32_system_axi_intc_0_0/esp32_system_axi_intc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==esp32_system_axi_intc_0_0 || ORIG_REF_NAME==esp32_system_axi_intc_0_0} -quiet] -quiet

# IP: F:/Project AHE/esp32_system/ip/esp32_system_PmodESP32_0_0/esp32_system_PmodESP32_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==esp32_system_PmodESP32_0_0 || ORIG_REF_NAME==esp32_system_PmodESP32_0_0} -quiet] -quiet

# IP: f:/Project AHE/esp32_system/ip/esp32_system_PmodOLEDrgb_0_0/esp32_system_PmodOLEDrgb_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==esp32_system_PmodOLEDrgb_0_0 || ORIG_REF_NAME==esp32_system_PmodOLEDrgb_0_0} -quiet] -quiet

# IP: f:/Project AHE/esp32_system/ip/esp32_system_axi_iic_0_0/esp32_system_axi_iic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==esp32_system_axi_iic_0_0 || ORIG_REF_NAME==esp32_system_axi_iic_0_0} -quiet] -quiet

# IP: f:/Project AHE/esp32_system/ip/esp32_system_xlconcat_0_0/esp32_system_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==esp32_system_xlconcat_0_0 || ORIG_REF_NAME==esp32_system_xlconcat_0_0} -quiet] -quiet

# XDC: F:/Project AHE/esp32_system/esp32_system_ooc.xdc
