# 
# Report generation script generated by Vivado
# 

if {$argv == "synth_design"} {
  set retval [open_checkpoint esp32_dlmb_v10_0.dcp]
  if { $retval == "checkpoint_esp32_dlmb_v10_0" } {
generate_parallel_reports -reports { "report_utilization -file esp32_dlmb_v10_0_utilization_synth.rpt -pb esp32_dlmb_v10_0_utilization_synth.pb"  } 
  
  close_design
  }
}
