# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/esp32/esp32/ip/esp32_dlmb_bram_if_cntlr_0/esp32_dlmb_bram_if_cntlr_0.xci
# IP: The module: 'esp32_dlmb_bram_if_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/esp32/esp32/ip/esp32_dlmb_bram_if_cntlr_0/esp32_dlmb_bram_if_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'esp32_dlmb_bram_if_cntlr_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: f:/esp32/esp32/ip/esp32_dlmb_bram_if_cntlr_0/esp32_dlmb_bram_if_cntlr_0.xci
# IP: The module: 'esp32_dlmb_bram_if_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/esp32/esp32/ip/esp32_dlmb_bram_if_cntlr_0/esp32_dlmb_bram_if_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'esp32_dlmb_bram_if_cntlr_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
