# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/Advance Hardware Eng/Lab_4/Design_MicroBlaze/ip/Design_MicroBlaze_microblaze_0_0/Design_MicroBlaze_microblaze_0_0.xci
# IP: The module: 'Design_MicroBlaze_microblaze_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Advance Hardware Eng/Lab_4/Design_MicroBlaze/ip/Design_MicroBlaze_microblaze_0_0/Design_MicroBlaze_microblaze_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Design_MicroBlaze_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: f:/Advance Hardware Eng/Lab_4/Design_MicroBlaze/ip/Design_MicroBlaze_microblaze_0_0/Design_MicroBlaze_microblaze_0_0_ooc_debug.xdc
# XDC: The top module name and the constraint reference have the same name: 'Design_MicroBlaze_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: f:/Advance Hardware Eng/Lab_4/Design_MicroBlaze/ip/Design_MicroBlaze_microblaze_0_0/Design_MicroBlaze_microblaze_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Design_MicroBlaze_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: f:/Advance Hardware Eng/Lab_4/Design_MicroBlaze/ip/Design_MicroBlaze_microblaze_0_0/Design_MicroBlaze_microblaze_0_0.xci
# IP: The module: 'Design_MicroBlaze_microblaze_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Advance Hardware Eng/Lab_4/Design_MicroBlaze/ip/Design_MicroBlaze_microblaze_0_0/Design_MicroBlaze_microblaze_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Design_MicroBlaze_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: f:/Advance Hardware Eng/Lab_4/Design_MicroBlaze/ip/Design_MicroBlaze_microblaze_0_0/Design_MicroBlaze_microblaze_0_0_ooc_debug.xdc
# XDC: The top module name and the constraint reference have the same name: 'Design_MicroBlaze_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: f:/Advance Hardware Eng/Lab_4/Design_MicroBlaze/ip/Design_MicroBlaze_microblaze_0_0/Design_MicroBlaze_microblaze_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Design_MicroBlaze_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
