# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: F:/Advance Hardware Eng/Lab_4/Design_MicroBlaze/Design_MicroBlaze.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Design_MicroBlaze || ORIG_REF_NAME==Design_MicroBlaze} -quiet] -quiet

# IP: f:/Advance Hardware Eng/Lab_4/Design_MicroBlaze/ip/Design_MicroBlaze_microblaze_0_0/Design_MicroBlaze_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Design_MicroBlaze_microblaze_0_0 || ORIG_REF_NAME==Design_MicroBlaze_microblaze_0_0} -quiet] -quiet

# IP: f:/Advance Hardware Eng/Lab_4/Design_MicroBlaze/ip/Design_MicroBlaze_dlmb_v10_0/Design_MicroBlaze_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Design_MicroBlaze_dlmb_v10_0 || ORIG_REF_NAME==Design_MicroBlaze_dlmb_v10_0} -quiet] -quiet

# IP: f:/Advance Hardware Eng/Lab_4/Design_MicroBlaze/ip/Design_MicroBlaze_ilmb_v10_0/Design_MicroBlaze_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Design_MicroBlaze_ilmb_v10_0 || ORIG_REF_NAME==Design_MicroBlaze_ilmb_v10_0} -quiet] -quiet

# IP: f:/Advance Hardware Eng/Lab_4/Design_MicroBlaze/ip/Design_MicroBlaze_dlmb_bram_if_cntlr_0/Design_MicroBlaze_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Design_MicroBlaze_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==Design_MicroBlaze_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: f:/Advance Hardware Eng/Lab_4/Design_MicroBlaze/ip/Design_MicroBlaze_ilmb_bram_if_cntlr_0/Design_MicroBlaze_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Design_MicroBlaze_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==Design_MicroBlaze_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: f:/Advance Hardware Eng/Lab_4/Design_MicroBlaze/ip/Design_MicroBlaze_lmb_bram_0/Design_MicroBlaze_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Design_MicroBlaze_lmb_bram_0 || ORIG_REF_NAME==Design_MicroBlaze_lmb_bram_0} -quiet] -quiet

# IP: f:/Advance Hardware Eng/Lab_4/Design_MicroBlaze/ip/Design_MicroBlaze_microblaze_0_axi_periph_imp_xbar_0/Design_MicroBlaze_microblaze_0_axi_periph_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Design_MicroBlaze_microblaze_0_axi_periph_imp_xbar_0 || ORIG_REF_NAME==Design_MicroBlaze_microblaze_0_axi_periph_imp_xbar_0} -quiet] -quiet

# IP: f:/Advance Hardware Eng/Lab_4/Design_MicroBlaze/ip/Design_MicroBlaze_microblaze_0_axi_periph_0/Design_MicroBlaze_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Design_MicroBlaze_microblaze_0_axi_periph_0 || ORIG_REF_NAME==Design_MicroBlaze_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: f:/Advance Hardware Eng/Lab_4/Design_MicroBlaze/ip/Design_MicroBlaze_microblaze_0_axi_intc_0/Design_MicroBlaze_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Design_MicroBlaze_microblaze_0_axi_intc_0 || ORIG_REF_NAME==Design_MicroBlaze_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: f:/Advance Hardware Eng/Lab_4/Design_MicroBlaze/ip/Design_MicroBlaze_microblaze_0_xlconcat_0/Design_MicroBlaze_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Design_MicroBlaze_microblaze_0_xlconcat_0 || ORIG_REF_NAME==Design_MicroBlaze_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: f:/Advance Hardware Eng/Lab_4/Design_MicroBlaze/ip/Design_MicroBlaze_mdm_1_0/Design_MicroBlaze_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Design_MicroBlaze_mdm_1_0 || ORIG_REF_NAME==Design_MicroBlaze_mdm_1_0} -quiet] -quiet

# IP: f:/Advance Hardware Eng/Lab_4/Design_MicroBlaze/ip/Design_MicroBlaze_clk_wiz_1_0/Design_MicroBlaze_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Design_MicroBlaze_clk_wiz_1_0 || ORIG_REF_NAME==Design_MicroBlaze_clk_wiz_1_0} -quiet] -quiet

# IP: f:/Advance Hardware Eng/Lab_4/Design_MicroBlaze/ip/Design_MicroBlaze_rst_clk_wiz_1_100M_0/Design_MicroBlaze_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Design_MicroBlaze_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==Design_MicroBlaze_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: f:/Advance Hardware Eng/Lab_4/Design_MicroBlaze/ip/Design_MicroBlaze_axi_uartlite_0_0/Design_MicroBlaze_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Design_MicroBlaze_axi_uartlite_0_0 || ORIG_REF_NAME==Design_MicroBlaze_axi_uartlite_0_0} -quiet] -quiet

# XDC: F:/Advance Hardware Eng/Lab_4/Design_MicroBlaze/Design_MicroBlaze_ooc.xdc
