# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: F:/esp32/pins.xdc

# Block Designs: F:/esp32/esp32/esp32.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==esp32 || ORIG_REF_NAME==esp32} -quiet] -quiet

# IP: f:/esp32/esp32/ip/esp32_microblaze_0_0/esp32_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==esp32_microblaze_0_0 || ORIG_REF_NAME==esp32_microblaze_0_0} -quiet] -quiet

# IP: f:/esp32/esp32/ip/esp32_dlmb_v10_0/esp32_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==esp32_dlmb_v10_0 || ORIG_REF_NAME==esp32_dlmb_v10_0} -quiet] -quiet

# IP: f:/esp32/esp32/ip/esp32_ilmb_v10_0/esp32_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==esp32_ilmb_v10_0 || ORIG_REF_NAME==esp32_ilmb_v10_0} -quiet] -quiet

# IP: f:/esp32/esp32/ip/esp32_dlmb_bram_if_cntlr_0/esp32_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==esp32_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==esp32_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: f:/esp32/esp32/ip/esp32_ilmb_bram_if_cntlr_0/esp32_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==esp32_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==esp32_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: f:/esp32/esp32/ip/esp32_lmb_bram_0/esp32_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==esp32_lmb_bram_0 || ORIG_REF_NAME==esp32_lmb_bram_0} -quiet] -quiet

# IP: f:/esp32/esp32/ip/esp32_mdm_1_0/esp32_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==esp32_mdm_1_0 || ORIG_REF_NAME==esp32_mdm_1_0} -quiet] -quiet

# IP: f:/esp32/esp32/ip/esp32_clk_wiz_1_0/esp32_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==esp32_clk_wiz_1_0 || ORIG_REF_NAME==esp32_clk_wiz_1_0} -quiet] -quiet

# IP: f:/esp32/esp32/ip/esp32_rst_clk_wiz_1_100M_0/esp32_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==esp32_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==esp32_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: f:/esp32/esp32/ip/esp32_axi_uartlite_1_0/esp32_axi_uartlite_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==esp32_axi_uartlite_1_0 || ORIG_REF_NAME==esp32_axi_uartlite_1_0} -quiet] -quiet

# IP: f:/esp32/esp32/ip/esp32_axi_smc_0/esp32_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==esp32_axi_smc_0 || ORIG_REF_NAME==esp32_axi_smc_0} -quiet] -quiet

# IP: f:/esp32/esp32/ip/esp32_reset_inv_0_0/esp32_reset_inv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==esp32_reset_inv_0_0 || ORIG_REF_NAME==esp32_reset_inv_0_0} -quiet] -quiet

# IP: f:/esp32/esp32/ip/esp32_axi_intc_0_0/esp32_axi_intc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==esp32_axi_intc_0_0 || ORIG_REF_NAME==esp32_axi_intc_0_0} -quiet] -quiet

# IP: f:/esp32/esp32/ip/esp32_PmodESP32_0_1/esp32_PmodESP32_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==esp32_PmodESP32_0_1 || ORIG_REF_NAME==esp32_PmodESP32_0_1} -quiet] -quiet

# XDC: F:/esp32/esp32/esp32_ooc.xdc
