domain_path: F:\AHE_Final_Labs\hello_demo\export\hello_demo\sw\standalone_microblaze_0
app_src_dir: D:\Xilinx\2025.1\Vitis\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
