# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "F:/esp32/esp32.runs/synth_1/esp32_system_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 2
set_param general.usePosixSpawnForFork 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/esp32/esp32.cache/wt [current_project]
set_property parent.project_path F:/esp32/esp32.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys-a7-100t:part0:1.3 [current_project]
set_property ip_repo_paths f:/vivado-library [current_project]
update_ip_catalog
set_property ip_output_repo f:/esp32/esp32.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib {{F:/Project AHE/esp32_system/hdl/esp32_system_wrapper.v}}
add_files {{F:/Project AHE/esp32_system/esp32_system.bd}}
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_microblaze_0_0/esp32_system_microblaze_0_0.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_microblaze_0_0/esp32_system_microblaze_0_0_ooc_debug.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_microblaze_0_0/esp32_system_microblaze_0_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_dlmb_v10_0/esp32_system_dlmb_v10_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_ilmb_v10_0/esp32_system_ilmb_v10_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_dlmb_bram_if_cntlr_0/esp32_system_dlmb_bram_if_cntlr_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_ilmb_bram_if_cntlr_0/esp32_system_ilmb_bram_if_cntlr_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_lmb_bram_0/esp32_system_lmb_bram_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_mdm_1_0/esp32_system_mdm_1_0.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_mdm_1_0/esp32_system_mdm_1_0_ooc_trace.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_clk_wiz_1_0/esp32_system_clk_wiz_1_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_clk_wiz_1_0/esp32_system_clk_wiz_1_0.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_clk_wiz_1_0/esp32_system_clk_wiz_1_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_rst_clk_wiz_1_100M_0/esp32_system_rst_clk_wiz_1_100M_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_rst_clk_wiz_1_100M_0/esp32_system_rst_clk_wiz_1_100M_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_uartlite_1_0/esp32_system_axi_uartlite_1_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_uartlite_1_0/esp32_system_axi_uartlite_1_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_1/bd_7fbf_psr_aclk_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_2/bd_7fbf_arinsw_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_3/bd_7fbf_rinsw_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_4/bd_7fbf_awinsw_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_5/bd_7fbf_winsw_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_6/bd_7fbf_binsw_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_7/bd_7fbf_aroutsw_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_8/bd_7fbf_routsw_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_9/bd_7fbf_awoutsw_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_10/bd_7fbf_woutsw_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_11/bd_7fbf_boutsw_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_12/bd_7fbf_arni_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_13/bd_7fbf_rni_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_14/bd_7fbf_awni_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_15/bd_7fbf_wni_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_16/bd_7fbf_bni_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_20/bd_7fbf_s00a2s_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_21/bd_7fbf_sarn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_22/bd_7fbf_srn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_23/bd_7fbf_sawn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_24/bd_7fbf_swn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_25/bd_7fbf_sbn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_26/bd_7fbf_m00s2a_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_27/bd_7fbf_m00arn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_28/bd_7fbf_m00rn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_29/bd_7fbf_m00awn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_30/bd_7fbf_m00wn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_31/bd_7fbf_m00bn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_33/bd_7fbf_m01s2a_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_34/bd_7fbf_m01arn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_35/bd_7fbf_m01rn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_36/bd_7fbf_m01awn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_37/bd_7fbf_m01wn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_38/bd_7fbf_m01bn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_40/bd_7fbf_m02s2a_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_41/bd_7fbf_m02arn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_42/bd_7fbf_m02rn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_43/bd_7fbf_m02awn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_44/bd_7fbf_m02wn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_45/bd_7fbf_m02bn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_47/bd_7fbf_m03s2a_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_48/bd_7fbf_m03arn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_49/bd_7fbf_m03rn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_50/bd_7fbf_m03awn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_51/bd_7fbf_m03wn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_52/bd_7fbf_m03bn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_54/bd_7fbf_m04s2a_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_55/bd_7fbf_m04arn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_56/bd_7fbf_m04rn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_57/bd_7fbf_m04awn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_58/bd_7fbf_m04wn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_59/bd_7fbf_m04bn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_61/bd_7fbf_m05s2a_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_62/bd_7fbf_m05arn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_63/bd_7fbf_m05rn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_64/bd_7fbf_m05awn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_65/bd_7fbf_m05wn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_66/bd_7fbf_m05bn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_68/bd_7fbf_m06s2a_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_69/bd_7fbf_m06arn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_70/bd_7fbf_m06rn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_71/bd_7fbf_m06awn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_72/bd_7fbf_m06wn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/bd_0/ip/ip_73/bd_7fbf_m06bn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_smc_0/smartconnect.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_intc_0_0/esp32_system_axi_intc_0_0.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_intc_0_0/esp32_system_axi_intc_0_0_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_intc_0_0/esp32_system_axi_intc_0_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_PmodESP32_0_0/src/PmodESP32_pmod_bridge_0_0/PmodESP32_pmod_bridge_0_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_PmodESP32_0_0/src/PmodESP32_pmod_bridge_0_0/src/pmod_concat_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_PmodESP32_0_0/esp32_system_PmodESP32_0_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_PmodESP32_0_0/src/PmodESP32_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_PmodESP32_0_0/src/PmodESP32_axi_uartlite_0_0/PmodESP32_axi_uartlite_0_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_PmodESP32_0_0/src/PmodESP32_axi_uartlite_0_0/PmodESP32_axi_uartlite_0_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_PmodESP32_0_0/src/PmodESP32_axi_gpio_0_0/PmodESP32_axi_gpio_0_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_PmodESP32_0_0/src/PmodESP32_axi_gpio_0_0/PmodESP32_axi_gpio_0_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_PmodOLEDrgb_0_0/ip/PmodOLEDrgb_axi_quad_spi_0_0/PmodOLEDrgb_axi_quad_spi_0_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_PmodOLEDrgb_0_0/ip/PmodOLEDrgb_axi_quad_spi_0_0/PmodOLEDrgb_axi_quad_spi_0_0.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_PmodOLEDrgb_0_0/ip/PmodOLEDrgb_axi_quad_spi_0_0/PmodOLEDrgb_axi_quad_spi_0_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_PmodOLEDrgb_0_0/ip/PmodOLEDrgb_axi_quad_spi_0_0/PmodOLEDrgb_axi_quad_spi_0_0_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_PmodOLEDrgb_0_0/esp32_system_PmodOLEDrgb_0_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_PmodOLEDrgb_0_0/ip/PmodOLEDrgb_axi_gpio_0_1/PmodOLEDrgb_axi_gpio_0_1_board.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_PmodOLEDrgb_0_0/ip/PmodOLEDrgb_axi_gpio_0_1/PmodOLEDrgb_axi_gpio_0_1_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_PmodOLEDrgb_0_0/ip/PmodOLEDrgb_pmod_bridge_0_0/PmodOLEDrgb_pmod_bridge_0_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_PmodOLEDrgb_0_0/ip/PmodOLEDrgb_pmod_bridge_0_0/src/pmod_concat_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_iic_0_0/esp32_system_axi_iic_0_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_axi_iic_0_0/esp32_system_axi_iic_0_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{F:/Project AHE/esp32_system/esp32_system_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{f:/Project AHE/esp32_system/ip/esp32_system_microblaze_0_0/data/mb_bootloop_le.elf}}]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/esp32/pins.xdc
set_property used_in_implementation false [get_files F:/esp32/pins.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental F:/esp32/esp32.srcs/utils_1/imports/synth_1/esp32_wrapper.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top esp32_system_wrapper -part xc7a100tcsg324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef esp32_system_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file esp32_system_wrapper_utilization_synth.rpt -pb esp32_system_wrapper_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
