# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: F:/AHE_Final_Labs/Lab_2/Exercise_1/counter_circuit_4_bit/counter_circuit_4_bit.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==counter_circuit_4_bit || ORIG_REF_NAME==counter_circuit_4_bit} -quiet] -quiet

# IP: f:/AHE_Final_Labs/Lab_2/Exercise_1/counter_circuit_4_bit/ip/counter_circuit_4_bit_up_down_counter_4bit_0_0/counter_circuit_4_bit_up_down_counter_4bit_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==counter_circuit_4_bit_up_down_counter_4bit_0_0 || ORIG_REF_NAME==counter_circuit_4_bit_up_down_counter_4bit_0_0} -quiet] -quiet

# XDC: F:/AHE_Final_Labs/Lab_2/Exercise_1/counter_circuit_4_bit/counter_circuit_4_bit_ooc.xdc
